/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import { useGLTF } from "@react-three/drei";
import React, { useRef } from "react";
import * as THREE from "three";
import { GLTF } from "three/examples/jsm/loaders/GLTFLoader";

type GLTFResult = GLTF & {
  nodes: {
    fox_1: THREE.Mesh;
    fox_2: THREE.Mesh;
    fox_3: THREE.Mesh;
    fox_4: THREE.Mesh;
    fox_5: THREE.Mesh;
    fox_6: THREE.Mesh;
    fox_7: THREE.Mesh;
    fox_8: THREE.Mesh;
    fox_9: THREE.Mesh;
    fox_10: THREE.Mesh;
  };
  materials: {
    ["fox2:material_0"]: THREE.MeshStandardMaterial;
    ["fox2:material_2"]: THREE.MeshStandardMaterial;
    ["fox2:material_4"]: THREE.MeshStandardMaterial;
    ["fox2:material_6"]: THREE.MeshStandardMaterial;
    ["fox2:material_8"]: THREE.MeshStandardMaterial;
    ["fox2:material_10"]: THREE.MeshStandardMaterial;
    ["fox2:material_12"]: THREE.MeshStandardMaterial;
    ["fox2:material_14"]: THREE.MeshStandardMaterial;
    ["fox2:material_16"]: THREE.MeshStandardMaterial;
    ["fox2:material_18"]: THREE.MeshStandardMaterial;
  };
};

export default function Model(props: JSX.IntrinsicElements["group"]) {
  const group = useRef<THREE.Group>();
  const { nodes, materials } = useGLTF("/fox.glb") as GLTFResult;
  return (
    // @ts-ignore
    <group ref={group} {...props} dispose={null}>
      <group
        rotation={[Math.PI / 2, 0, 0]}
        scale={[0.00363146, 0.00363146, 0.00363146]}
      >
        <mesh
          geometry={nodes.fox_1.geometry}
          material={materials["fox2:material_0"]}
        />
        <mesh
          geometry={nodes.fox_2.geometry}
          material={materials["fox2:material_2"]}
        />
        <mesh
          geometry={nodes.fox_3.geometry}
          material={materials["fox2:material_4"]}
        />
        <mesh
          geometry={nodes.fox_4.geometry}
          material={materials["fox2:material_6"]}
        />
        <mesh
          geometry={nodes.fox_5.geometry}
          material={materials["fox2:material_8"]}
        />
        <mesh
          geometry={nodes.fox_6.geometry}
          material={materials["fox2:material_10"]}
        />
        <mesh
          geometry={nodes.fox_7.geometry}
          material={materials["fox2:material_12"]}
        />
        <mesh
          geometry={nodes.fox_8.geometry}
          material={materials["fox2:material_14"]}
        />
        <mesh
          geometry={nodes.fox_9.geometry}
          material={materials["fox2:material_16"]}
        />
        <mesh
          geometry={nodes.fox_10.geometry}
          material={materials["fox2:material_18"]}
        />
      </group>
    </group>
  );
}

useGLTF.preload("/fox.glb");
